from dataclasses import dataclass
from .blanket_base import BlanketLayer, Blanket, OpenMCBlanketSimulation
from typing import List , Literal, Iterable, Tuple
import openmc
from functools import cached_property
import numpy as np
from typing import Union
@dataclass
class BlanketLayer1D(BlanketLayer):
    thickness : float  # in meters

@dataclass
class Blanket1D(Blanket):
    size_yz : float  # in meters
    prism_boundary_type : str = 'periodic'  # e.g., 'reflective', 'vacuum', etc.
    plasma_boundary_type : str = 'vacuum'

    @property     
    def average_thickness(self):
        return sum([layer.thickness for layer in self.layers[1:]])

    
@dataclass
class OpenMCLinearBlanketSimulation(OpenMCBlanketSimulation):
    n_x_spacing_tally : int 
    energy_bins     : Iterable[float]
    source_strength : float = 1.0
    tally_types     : Tuple[Literal["flux", "heating", "tritium"]] = ("flux", "heating", "tritium")
            
    @cached_property    
    def geometry(self):
        return _create_1D_geometry(
            blanket           = self.blanket,
            size_yz          = self.blanket.size_yz,
            prism_boundary_type = self.blanket.prism_boundary_type,
            plasma_boundary_type = self.blanket.plasma_boundary_type,
            material_list    = self.materials
        )

    @cached_property    
    def tallies(self):
        x_extent = np.linspace(self.geometry.bounding_box[0][0], self.geometry.bounding_box[1][0], self.n_x_spacing_tally  + 1)
        return _create_linear_openmc_tallies(
            x_spacing      = x_extent,
            egfilter       = self.energy_bins,
            openmc_geometry = self.geometry,
            types          = ["flux", "heating", "tritium"]
        )
        

    @cached_property    
    def source(self):
        return _create_linear_openmc_source(
            geometry       = self.geometry,
            source_strength = self.source_strength
        )
    
    
    def get_tally_results(self, sp_file : Union[str, None] = None, quantities : List[Literal["mean", "std", "rel_err"]] = ["mean"]):
        '''
        Function to extract the tally results from the OpenMC statepoint file

        Ensure that the statepoint file is generated by this object, otherwise the tallies may not be present.
        
        Parameters
        ----------
        sp_file : str
            The path to the OpenMC statepoint file
        quantities : List[Literal["mean", "std", "rel_err"]]
            A list of statistical quantities to extract from the tally results. Default is ["mean"].
        Returns
        -------
        result : dict
            A dictionary containing the tally results for each tally in the simulation. These results are also a dictionary indexed by the requested statistical quantities.
        -------        
        '''
        
        if sp_file is None:
            sp_file = self.sp_file

        if sp_file is None:
            raise ValueError("No statepoint file provided and simulation has not been run yet. Please run the simulation first or provide a specific statepoint file.")
        result = {}
        with openmc.StatePoint(sp_file) as sp:            
            for tally in self.tallies:                
                sp_tally     = sp.tallies[tally.id]
                mesh_data    = sp_tally.find_filter(openmc.MeshFilter).mesh
                # here only x-dependent data is extracted, consistent with a 1D simulation...
                result[sp_tally.name] = {}
                for quantity in quantities:
                    if quantity not in ["mean", "std_dev", "rel_err"]:
                        raise ValueError(f"Quantity {quantity} not supported. Supported quantities are: ['mean', 'std_dev', 'rel_err']")                    
                    if quantity == "rel_err":
                        divisor = 1.0
                    else:
                        divisor =  mesh_data.volumes[:,0,0, np.newaxis]  
                    result[sp_tally.name][quantity] =  np.flip(sp_tally.get_reshaped_data(quantity, expand_dims = True)[:,0,0,:,0,0] / divisor, axis=1)
                result[sp_tally.name]['x'] = mesh_data.x_grid
            result['runtime'] = sp.runtime['simulation']
            result['tally_volume'] = mesh_data.volumes[:,0,0]
        return result


    
@dataclass
class OpenMCSymmetricLinearBlanketSimulation(OpenMCLinearBlanketSimulation):
    n_x_spacing_tally : int 
    energy_bins     : Iterable[float]
    source_strength : float = 1.0
    tally_types     : Tuple[Literal["flux", "heating", "tritium"]] = ("flux", "heating", "tritium")
            
    @cached_property    
    def geometry(self):
        return _create_1D_geometry_symmetrized(
            blanket           = self.blanket,
            size_yz          = self.blanket.size_yz,
            prism_boundary_type = self.blanket.prism_boundary_type,
            plasma_boundary_type = self.blanket.plasma_boundary_type,
            material_list    = self.materials
        )

    

    
    


def _create_1D_geometry(blanket : Blanket, size_yz : float, prism_boundary_type : str, plasma_boundary_type : str, material_list : List[openmc.Material]) -> openmc.Geometry:
    import openmc
    import numpy as np

    is_blanket_layers = [isinstance(i, BlanketLayer1D) for i in blanket.layers]
    if not all(is_blanket_layers):
        raise ValueError("All layers in the blanket must be of type BlanketLayer1D to create a 1D geometry.")
        
    prism = openmc.model.RectangularPrism(size_yz * 100.0, size_yz * 100.0, boundary_type=prism_boundary_type, axis = 'x')    
    cumulative_thicknessess =[0] +list(np.cumsum([layer_i.thickness for layer_i in blanket.layers]))
    enddict  = [openmc.XPlane(x0 = j * 100) for j in cumulative_thicknessess]
    enddict[0].boundary_type  = plasma_boundary_type    
    enddict[-1].boundary_type = "vacuum"   
    
    cells = [openmc.Cell(fill = material_list[i], region = -prism & + enddict[i] & - enddict[i+1], name = layer.name) for i, layer in enumerate(blanket.layers)]
    
    
    geom = openmc.Geometry(cells)

    return geom



def _create_1D_geometry_symmetrized(blanket : Blanket, size_yz : float, prism_boundary_type : str, plasma_boundary_type : str, material_list : List[openmc.Material]) -> openmc.Geometry:
    import openmc
    import numpy as np

    is_blanket_layers = [isinstance(i, BlanketLayer1D) for i in blanket.layers]
    if not all(is_blanket_layers):
        raise ValueError("All layers in the blanket must be of type BlanketLayer1D to create a 1D geometry.")
        
    prism = openmc.model.RectangularPrism(size_yz * 100.0, size_yz * 100.0, boundary_type=prism_boundary_type, axis = 'x')    
    cumsum_values = np.cumsum([layer_i.thickness for layer_i in blanket.layers])
    cumulative_thicknessess =list(-np.flip(cumsum_values)) +list(cumsum_values)
    
    enddict  = [openmc.XPlane(x0 = j * 100) for j in cumulative_thicknessess]
    enddict[0].boundary_type  = 'vacuum'  
    enddict[-1].boundary_type = "vacuum"   
    
    materials_symmetrized = list(reversed(material_list)) +  material_list[1:]
    names_symmetrized     = [layer.name + "_symm" for layer in reversed(blanket.layers)] + [layer.name for layer in blanket.layers[1:]]
        
    cells = [openmc.Cell(fill = materials_symmetrized[i], region = -prism & + enddict[i] & - enddict[i+1], name = names_symmetrized[i]) for i, _ in enumerate(materials_symmetrized)]
    
    
    geom = openmc.Geometry(cells)

    return geom

def _create_linear_openmc_source(geometry, source_strength):    
    '''
    Function to create an OpenMC source for the 1D breeding blanket in the plasma region

    Creates an independent source in the plasma region with a uniform spatial distribution, isotropic angular distribution, and a fixed energy of 14.1 MeV.

    Parameters
    ----------
    geometry : openmc.Geometry
        The OpenMC geometry object for the breeding blanket
    source_strength : float
        The strength of the source in particles per cubic centimeters per second (default is 10.0)
        Does not matter much, as the final result is linear in this quantity.
    Returns
    -------
    plasma_source : openmc.IndependentSource
        The OpenMC independent source object for the plasma region
    -------
    '''
    plasma_source             = openmc.IndependentSource()    
    plasma_cell               = geometry.get_cells_by_name('Plasma')[0]
    plasma_source.constraints = {"domains": [plasma_cell]}
    plasma_source.space       = openmc.stats.Box(plasma_cell.bounding_box[0], plasma_cell.bounding_box[1])
    plasma_source.angle       = openmc.stats.Isotropic()
    plasma_source.energy      = openmc.stats.Discrete([14.1e6], [1.0])
    plasma_source.strength    = source_strength  * plasma_cell.bounding_box.volume    
    return plasma_source


def _create_linear_openmc_tallies(x_spacing, egfilter : Iterable[float], openmc_geometry : openmc.Geometry,  types : List[Literal["flux", "heating", "tritium"]] = ["flux", "heating", "tritium"]):

    try:
    
        egfilter = openmc.EnergyFilter(egfilter)
    except:        
        egfilter = openmc.EnergyFilter(np.flip(egfilter))
    smesh = openmc.RectilinearMesh()
    smesh.x_grid = x_spacing

    smesh.y_grid = [openmc_geometry.bounding_box[0][1], openmc_geometry.bounding_box[1][1]]
    smesh.z_grid = [openmc_geometry.bounding_box[0][2], openmc_geometry.bounding_box[1][2]]
    meshfilter     = openmc.MeshFilter(smesh)
    type_to_tally = {
        "flux" : "flux",
        "heating" : "heating",
        "tritium" : "(n,Xt)"
    }
    
    tallies = openmc.Tallies()
    for type_i in types:
        if type_i not in type_to_tally:
            raise ValueError(f"Type {type_i} not supported. Supported types are: {list(type_to_tally.keys())}")
        tally_i         = openmc.Tally()
        tally_i.filters = [meshfilter, egfilter]
        tally_i.scores  = [type_to_tally[type_i]]
        tally_i.name    = type_i 

        tallies.append(tally_i)
        
    return tallies