from dataclasses import dataclass
from .blanket_base import BlanketLayer, Blanket, OpenMCBlanketSimulation
from typing import Dict, List , Literal, Iterable, Tuple
import openmc
from functools import cached_property
import numpy as onp
from typing import Union
from os import PathLike
import os
@dataclass
class BlanketLayer1D(BlanketLayer):
    thickness : float  # in meters

@dataclass
class Blanket1D(Blanket):
    size_yz : float  # in meters
    prism_boundary_type : str = 'periodic'  # e.g., 'reflective', 'vacuum', etc.
    plasma_boundary_type : str = 'vacuum'

    @property     
    def average_thicknesses(self):
        return self.thicknesses

    @property
    def thicknesses(self):
        return [layer.thickness for layer in self.layers]
    
@dataclass
class OpenMCLinearBlanketSimulation(OpenMCBlanketSimulation):
    n_x_spacing_tally : int 
    energy_bins     : Iterable[float]
    source_strength : float = 1.0
    tally_types     : Tuple[Literal["flux", "heating", "tritium"]] = ("flux", "heating", "tritium")

    sp_file         : Union[os.PathLike, None] = None
            
    @cached_property    
    def geometry(self):
        return _create_1D_geometry(
            blanket           = self.blanket,
            size_yz          = self.blanket.size_yz,
            prism_boundary_type = self.blanket.prism_boundary_type,
            plasma_boundary_type = self.blanket.plasma_boundary_type,
            material_list    = self.materials
        )

    @cached_property    
    def tallies(self):
        x_extent = onp.linspace(self.geometry.bounding_box[0][0], self.geometry.bounding_box[1][0], self.n_x_spacing_tally  + 1)
        return _create_linear_openmc_tallies(
            x_spacing      = x_extent,
            egfilter       = self.energy_bins,
            openmc_geometry = self.geometry,
            types          = ["flux", "heating", "tritium"]
        )
        

    @cached_property    
    def source(self):
        return _create_linear_openmc_source(
            geometry       = self.geometry,
            source_strength = self.source_strength
        )
    
    
    def get_tally_results(self, sp_file : Union[str, None] = None, quantities : List[Literal["mean", "std", "rel_err"]] = ["mean"]):
        '''
        Function to extract the tally results from the OpenMC statepoint file

        Ensure that the statepoint file is generated by this object, otherwise the tallies may not be present.
        
        Parameters
        ----------
        sp_file : str
            The path to the OpenMC statepoint file
        quantities : List[Literal["mean", "std", "rel_err"]]
            A list of statistical quantities to extract from the tally results. Default is ["mean"].
        Returns
        -------
        result : dict
            A dictionary containing the tally results for each tally in the simulation. These results are also a dictionary indexed by the requested statistical quantities.
        -------        
        '''
        
        if sp_file is None:
            sp_file = self.sp_file

        if sp_file is None:
            raise ValueError("No statepoint file provided and simulation has not been run yet. Please run the simulation first or provide a specific statepoint file.")
        result = {}
        with openmc.StatePoint(sp_file) as sp:            
            for tally in self.tallies:   
                sp_tally     = sp.get_tally(name = tally.name)
                mesh_data    = sp_tally.find_filter(openmc.MeshFilter).mesh
                # here only x-dependent data is extracted, consistent with a 1D simulation...
                result[sp_tally.name] = {}
                for quantity in quantities:
                    if quantity not in ["mean", "std_dev", "rel_err"]:
                        raise ValueError(f"Quantity {quantity} not supported. Supported quantities are: ['mean', 'std_dev', 'rel_err']")                    
                    if quantity == "rel_err":
                        divisor = 1.0
                    else:
                        divisor =  mesh_data.volumes[:,0,0, onp.newaxis]
                    result[sp_tally.name][quantity] =  onp.flip(sp_tally.get_reshaped_data(quantity, expand_dims = True)[:,0,0,:,0,0] / divisor, axis=1)
                result[sp_tally.name]['x'] = mesh_data.x_grid
            result['runtime'] = sp.runtime['simulation']
            result['tally_volume'] = mesh_data.volumes[:,0,0]
        return result


    
@dataclass
class OpenMCSymmetricLinearBlanketSimulation(OpenMCLinearBlanketSimulation):    
            
    @cached_property    
    def geometry(self):
        return _create_1D_geometry_symmetrized(
            blanket              = self.blanket,
            size_yz              = self.blanket.size_yz,
            prism_boundary_type  = self.blanket.prism_boundary_type,
            plasma_boundary_type = self.blanket.plasma_boundary_type,
            material_list        = self.materials
        )
    
    def _create_1d_importance_map_radial(self,  energy_groups_ww : onp.ndarray, n_x_importance_map : int = 100, legendre_order = 3, degree = 3, tn_order = 3, n_elem_per_region = 5, data_dict : Dict = None, **kwargs):
        '''
        Creates a 1D importance map in the radial direction

        Parameters
        ----------
        energy_groups_ww : onp.ndarray
            The energy group boundaries to use for the importance map generation. Must be in descending order for this function (same as jax-sn). Automatically flipped for OpenMC ordering
        '''
        if not onp.all(onp.sort(energy_groups_ww)[::-1] == onp.array(energy_groups_ww)):
            raise ValueError("Energy groups must be in descending order for this function (it uses the same ordering as jax-sn, namely descending). It is then automatically converted to OpenMC format (ascending)")
        if data_dict is None:
            mgxs_data_dict = self.create_mgxs_data_dict(onp.flip(energy_groups_ww), legendre_order, extra_types = [])[0]
        else:
            mgxs_data_dict = data_dict

        from .sn.base_sn import create_importance_map_for_blanket
        blanket_start  = sum(self.blanket.average_thicknesses[1:])   # re-compensate for symmetry (as in create_importance_map_for_blanket)...
        s_interp       = onp.linspace(-blanket_start, self.blanket.average_thickness, n_x_importance_map)
        importance_map = create_importance_map_for_blanket(self.blanket, mgxs_data_dict,  [n_elem_per_region for i in range(len(self.blanket.layers))], degree, tn_order,s_interp)    
        return s_interp + blanket_start, importance_map
    
    def create_weight_windows(self, energy_groups_ww : Iterable[float], degree  : int = 3, legendre_order : int = 3, tn_order : int = 3, n_elem_per_region : int = 5, ww_lower_upper_ratio : int = 3, ww_kwargs : Dict = None, data_dict : Dict = None, n_x_importance_map : int = 100, **kwargs):
        '''
        Creates weight windows for the blanket based on a forward-weighted CADIS importance map of a 1D blanket using the average thicknesses. 
        The weight windows are on the same mesh as the tally and the source. This reduces overhead of the mesh localization.

        Parameters:
        ----------
        data_dictionary : Dict
            A dictionary containing any additional data required to create the importance map. This is assumed to have the same keys as the blanket.layer_names property. The dictionary 
            values are a tuple of (total_cross_section, scattering_cross_section), where total_cross section is of shape [n_groups] and scattering_cross_section is of shape [l_order, n_groups, n_groups].
        
            

        degree : int
            The degree of the finite element basis to use for the importance map generation. Default is 3.
        tn_order : int
            The order of the Tn quadrature to use for the importance map generation. Default is 3.
        n_elem_per_region : int
            The number of finite elements to use per region in the importance map generation. Default is 5.
        ww_lower_upper_ratio : int
            The ratio of the lower to upper weight window values. Default is 3, meaning the upper weight window value is 3 times the lower weight window value. 
        **kwargs : dict
            Any additional keyword arguments to pass to the importance map generation function (which passes it directly to the multigroup operator creation, so it can be used to set different operators for the 
            multigroup operator, e.g. TransportOperatorVmapPallas instead of TransportOperatorVmap).
        '''
        from .openmc_base_functions import importance_map_to_weight_window
        if ww_kwargs is None:
            ww_kwargs = {"max_split" : 2000}
        if not onp.all(onp.sort(energy_groups_ww)[::-1] == onp.array(energy_groups_ww)):
            raise ValueError("Energy groups must be in descending order for this function (it uses the same ordering as jax-sn, namely descending). It is then automatically converted to OpenMC format (ascending)")
        s_interp, importance_map = self._create_1d_importance_map_radial(energy_groups_ww, n_x_importance_map, legendre_order, degree, tn_order, n_elem_per_region, data_dict, **kwargs)

        blanket_start = sum(self.blanket.average_thicknesses[1:])

        importance_map = onp.where(onp.logical_and(s_interp > blanket_start, s_interp < blanket_start + self.blanket.average_thicknesses[0]), onp.nan, importance_map) # set importance map to nan in the plasma region, as we do not want to generate weight windows there.
        # They will be automatically set to the maximum weight window value.
        importance_map_elem = 0.5 * (importance_map[:, :-1] + importance_map[:, 1:])

        mesh = openmc.RectilinearMesh()
        mesh.x_grid = onp.linspace(self.geometry.bounding_box[0][0], self.geometry.bounding_box[1][0], n_x_importance_map)
        mesh.y_grid = [self.geometry.bounding_box[0][1], self.geometry.bounding_box[1][1]]
        mesh.z_grid = [self.geometry.bounding_box[0][2], self.geometry.bounding_box[1][2]]

        return importance_map_to_weight_window(importance_map_elem, energy_groups_ww, mesh, ww_lower_upper_ratio, **ww_kwargs)


def _create_1D_geometry(blanket : Blanket, size_yz : float, prism_boundary_type : str, plasma_boundary_type : str, material_list : List[openmc.Material]) -> openmc.Geometry:
    is_blanket_layers = [isinstance(i, BlanketLayer1D) for i in blanket.layers]
    if not all(is_blanket_layers):
        raise ValueError("All layers in the blanket must be of type BlanketLayer1D to create a 1D geometry.")

    prism = openmc.model.RectangularPrism(size_yz * 100.0, size_yz * 100.0, boundary_type=prism_boundary_type, axis = 'x')
    cumulative_thicknessess =[0] +list(onp.cumsum([layer_i.thickness for layer_i in blanket.layers]))
    enddict  = [openmc.XPlane(x0 = j * 100) for j in cumulative_thicknessess]
    enddict[0].boundary_type  = plasma_boundary_type    
    enddict[-1].boundary_type = "vacuum"   
    
    cells = [openmc.Cell(fill = material_list[i], region = -prism & + enddict[i] & - enddict[i+1], name = layer.name) for i, layer in enumerate(blanket.layers)]
    
    
    geom = openmc.Geometry(cells)

    return geom



def _create_1D_geometry_symmetrized(blanket : Blanket, size_yz : float, prism_boundary_type : str, plasma_boundary_type : str, material_list : List[openmc.Material]) -> openmc.Geometry:
    '''
    Symmetrized geometry around the plasma. If there is no plasma, the geometry is symmetrized completely, including a double sized first layer.

    Parameters
    ----------
    blanket : Blanket
        The blanket object containing the layers and their properties
    size_yz : float
        The size of the geometry in the y and z directions, in meters
    prism_boundary_type : str
        The boundary type for the prism in the y and z directions (e.g., 'reflective', 'vacuum', etc.)
    plasma_boundary_type : str
        The boundary type for the plasma layer (e.g., 'reflective', 'vacuum', etc.). Unused here.
    material_list : List[openmc.Material]
        The list of OpenMC materials corresponding to the layers in the blanket, in the same order as the layers in the blanket
    Returns
    -------
    geom : openmc.Geometry
        The OpenMC geometry object for the symmetrized 1D blanket
    -------
    '''
    is_blanket_layers = [isinstance(i, BlanketLayer1D) for i in blanket.layers]
    if not all(is_blanket_layers):
        raise ValueError("All layers in the blanket must be of type BlanketLayer1D to create a 1D geometry.")

    prism = openmc.model.RectangularPrism(size_yz * 100.0, size_yz * 100.0, boundary_type=prism_boundary_type, axis = 'x')
    cumsum_values = onp.cumsum([layer_i.thickness / 2.0 if layer_i.name == "Plasma" else layer_i.thickness for layer_i in blanket.layers])
    cumulative_thicknessess =list(-onp.flip(cumsum_values)) +list(cumsum_values)

    cumulative_thicknessess = onp.array(cumulative_thicknessess) - onp.min(cumulative_thicknessess)  # shift so that the minimum is at 0, ensuring the first layer starts at 0
    
    enddict  = [openmc.XPlane(x0 = j * 100) for j in cumulative_thicknessess]
    enddict[0].boundary_type  = 'vacuum'  
    enddict[-1].boundary_type = "vacuum"   
    
    materials_symmetrized = list(reversed(material_list)) +  material_list[1:]
    names_symmetrized     = [layer.name + "_symm" for layer in reversed(blanket.layers)] + [layer.name for layer in blanket.layers[1:]]
        
    cells = [openmc.Cell(fill = materials_symmetrized[i], region = -prism & + enddict[i] & - enddict[i+1], name = names_symmetrized[i]) for i, _ in enumerate(materials_symmetrized)]
    
    
    geom = openmc.Geometry(cells)

    return geom

def _create_linear_openmc_source(geometry, source_strength):    
    '''
    Function to create an OpenMC source for the 1D breeding blanket in the plasma region

    Creates an independent source in the plasma region with a uniform spatial distribution, isotropic angular distribution, and a fixed energy of 14.1 MeV.

    Parameters
    ----------
    geometry : openmc.Geometry
        The OpenMC geometry object for the breeding blanket
    source_strength : float
        The strength of the source in particles per cubic centimeters per second (default is 10.0)
        Does not matter much, as the final result is linear in this quantity.
    Returns
    -------
    plasma_source : openmc.IndependentSource
        The OpenMC independent source object for the plasma region
    -------
    '''
    plasma_source             = openmc.IndependentSource()    
    plasma_cell               = geometry.get_cells_by_name('Plasma')[0]
    plasma_source.constraints = {"domains": [plasma_cell]}
    plasma_source.space       = openmc.stats.Box(plasma_cell.bounding_box[0], plasma_cell.bounding_box[1])
    plasma_source.angle       = openmc.stats.Isotropic()
    plasma_source.energy      = openmc.stats.Discrete([14.1e6], [1.0])
    plasma_source.strength    = source_strength  * plasma_cell.bounding_box.volume    
    return plasma_source


def _create_linear_openmc_tallies(x_spacing, egfilter : Iterable[float], openmc_geometry : openmc.Geometry,  types : List[Literal["flux", "heating", "tritium"]] = ["flux", "heating", "tritium"]):

    try:
        egfilter = openmc.EnergyFilter(egfilter)
    except Exception:
        egfilter = openmc.EnergyFilter(onp.flip(egfilter))
    smesh = openmc.RectilinearMesh()
    smesh.x_grid = x_spacing

    smesh.y_grid = [openmc_geometry.bounding_box[0][1], openmc_geometry.bounding_box[1][1]]
    smesh.z_grid = [openmc_geometry.bounding_box[0][2], openmc_geometry.bounding_box[1][2]]
    meshfilter     = openmc.MeshFilter(smesh)
    type_to_tally = {
        "flux" : "flux",
        "heating" : "heating",
        "tritium" : "(n,Xt)"
    }
    
    tallies = openmc.Tallies()
    for type_i in types:
        if type_i not in type_to_tally:
            raise ValueError(f"Type {type_i} not supported. Supported types are: {list(type_to_tally.keys())}")
        tally_i         = openmc.Tally()
        tally_i.filters = [meshfilter, egfilter]
        tally_i.scores  = [type_to_tally[type_i]]
        tally_i.name    = type_i 

        tallies.append(tally_i)
        
    return tallies